// Generated by reports/match-predictions/independent-leagues/train.mjs.
import { defineLeagueProfile } from '../leagueProfileRuntime.mjs';

export default defineLeagueProfile({
  "league": "T20 Matches",
  "algorithmId": "match-t20-matches-independent-v1",
  "profileVersion": "league-v1-6b9cdac57540",
  "strategy": "league-rules",
  "parameters": {
    "totalRatio": 1.5,
    "backRatio": 1.4
  },
  "baselineAdjustments": [],
  "model": null,
  "trainingTree": {
    "side": 0,
    "samples": 1
  },
  "trainingSamples": 1,
  "ranges": [
    [
      0.7582380347310462,
      0.7582380347310462
    ],
    [
      1,
      1
    ],
    [
      0.7644631509449534,
      0.7644631509449534
    ],
    [
      -0.8777040521581247,
      -0.8777040521581247
    ],
    [
      -0.3905636708756292,
      -0.3905636708756292
    ],
    [
      0.48714038128249554,
      0.48714038128249554
    ],
    [
      4.8054135174159684,
      4.8054135174159684
    ],
    [
      0.7221662197609495,
      0.7221662197609495
    ]
  ],
  "validationStatus": "insufficient-history",
  "evaluation": {
    "baseline": {
      "total": 1,
      "correct": 1,
      "wrong": 0,
      "accuracy": 100
    },
    "replay": {
      "total": 1,
      "correct": 1,
      "wrong": 0,
      "accuracy": 100
    },
    "trainingFit": {
      "total": 1,
      "correct": 1,
      "wrong": 0,
      "accuracy": 100
    },
    "walkForward": {
      "total": 1,
      "correct": 1,
      "wrong": 0,
      "accuracy": 100
    },
    "walkForwardBaseline": {
      "total": 1,
      "correct": 1,
      "wrong": 0,
      "accuracy": 100
    },
    "developmentFolds": [],
    "selection": "insufficient-history"
  },
  "datasetHash": "e6873555b28da50ccd6df1296c8b8b77f0cc8fca22098e7dd14ab867234f97e7"
});
