// Generated by reports/match-predictions/independent-leagues/train.mjs.
import { defineLeagueProfile } from '../leagueProfileRuntime.mjs';

export default defineLeagueProfile({
  "league": "Test Matches",
  "algorithmId": "match-test-matches-independent-v1",
  "profileVersion": "league-v1-2086a5bb517a",
  "strategy": "league-rules",
  "parameters": {
    "totalRatio": 1.5,
    "backRatio": 1.4
  },
  "baselineAdjustments": [],
  "model": null,
  "trainingTree": {
    "side": 0,
    "samples": 5
  },
  "trainingSamples": 5,
  "ranges": [
    [
      0.6470531974871134,
      0.9596877052202447
    ],
    [
      0.4562976108033241,
      0.9591105831240937
    ],
    [
      0.5896043953536138,
      0.9593907920660185
    ],
    [
      -1.118472120367023,
      0.024953931788736033
    ],
    [
      -0.5367602299919089,
      0.005064943014866303
    ],
    [
      -0.019888988773869732,
      0.5817118903751141
    ],
    [
      7.866438611329035,
      13.433546171939302
    ],
    [
      0.20060891836717484,
      0.780704631589988
    ]
  ],
  "validationStatus": "insufficient-history",
  "evaluation": {
    "baseline": {
      "total": 5,
      "correct": 5,
      "wrong": 0,
      "accuracy": 100
    },
    "replay": {
      "total": 5,
      "correct": 5,
      "wrong": 0,
      "accuracy": 100
    },
    "trainingFit": {
      "total": 5,
      "correct": 5,
      "wrong": 0,
      "accuracy": 100
    },
    "walkForward": {
      "total": 5,
      "correct": 5,
      "wrong": 0,
      "accuracy": 100
    },
    "walkForwardBaseline": {
      "total": 5,
      "correct": 5,
      "wrong": 0,
      "accuracy": 100
    },
    "developmentFolds": [],
    "selection": "insufficient-history"
  },
  "datasetHash": "e6873555b28da50ccd6df1296c8b8b77f0cc8fca22098e7dd14ab867234f97e7"
});
