// Generated by reports/match-predictions/independent-leagues/train.mjs.
import { defineLeagueProfile } from '../leagueProfileRuntime.mjs';

export default defineLeagueProfile({
  "league": "The Hundred",
  "algorithmId": "match-the-hundred-independent-v1",
  "profileVersion": "league-v1-73f92be33a2b",
  "strategy": "league-rules",
  "parameters": {
    "totalRatio": 1.5,
    "backRatio": 1.4
  },
  "baselineAdjustments": [],
  "model": null,
  "trainingTree": {
    "side": 0,
    "samples": 2
  },
  "trainingSamples": 2,
  "ranges": [
    [
      0.6923609954006755,
      0.9227399510600798
    ],
    [
      0.33135264938388465,
      0.5056837290643708
    ],
    [
      0.6359972379974743,
      0.8067206085135503
    ],
    [
      -1.473774874745106,
      -0.5161297070357214
    ],
    [
      -0.7253772089392623,
      -0.2500063695913861
    ],
    [
      0.2661233374443353,
      0.748397665805844
    ],
    [
      7.975588721457663,
      8.597363890898473
    ],
    [
      0.6291787853446311,
      0.8701574478359017
    ]
  ],
  "validationStatus": "insufficient-history",
  "evaluation": {
    "baseline": {
      "total": 2,
      "correct": 2,
      "wrong": 0,
      "accuracy": 100
    },
    "replay": {
      "total": 2,
      "correct": 2,
      "wrong": 0,
      "accuracy": 100
    },
    "trainingFit": {
      "total": 2,
      "correct": 2,
      "wrong": 0,
      "accuracy": 100
    },
    "walkForward": {
      "total": 2,
      "correct": 2,
      "wrong": 0,
      "accuracy": 100
    },
    "walkForwardBaseline": {
      "total": 2,
      "correct": 2,
      "wrong": 0,
      "accuracy": 100
    },
    "developmentFolds": [],
    "selection": "insufficient-history"
  },
  "datasetHash": "e6873555b28da50ccd6df1296c8b8b77f0cc8fca22098e7dd14ab867234f97e7"
});
