// Generated by normal-rule-tuning/tune.mjs. In-sample rule tuning; not calibrated accuracy.
export const LEAGUE_PREMATCH_ADJUSTMENTS = {
  "Emirates D10 League": {
    "samples": 1,
    "rules": [],
    "family": "frozen-base",
    "selection": "insufficient-data"
  },
  "Women's National Cricket League": {
    "samples": 0,
    "rules": [],
    "family": "frozen-base",
    "selection": "insufficient-data"
  },
  "ACC Men's Premier Cup": {
    "samples": 20,
    "rules": [],
    "family": "frozen-base",
    "selection": "candidate-temporal-regression"
  },
  "Asian Games Men": {
    "samples": 1,
    "rules": [],
    "family": "frozen-base",
    "selection": "insufficient-data"
  },
  "Asian Games T20": {
    "samples": 3,
    "rules": [],
    "family": "frozen-base",
    "selection": "insufficient-data"
  },
  "Asian Games Women": {
    "samples": 2,
    "rules": [],
    "family": "frozen-base",
    "selection": "insufficient-data"
  },
  "Australia One Day Cup": {
    "samples": 3,
    "rules": [],
    "family": "frozen-base",
    "selection": "insufficient-data"
  },
  "CSA Womens Pro50": {
    "samples": 0,
    "rules": [],
    "family": "frozen-base",
    "selection": "insufficient-data"
  },
  "CSA One-Day Challenge Div 2": {
    "samples": 2,
    "rules": [],
    "family": "frozen-base",
    "selection": "insufficient-data"
  },
  "Canada Super 60": {
    "samples": 2,
    "rules": [],
    "family": "frozen-base",
    "selection": "insufficient-data"
  },
  "Canada Super 60 Women": {
    "samples": 0,
    "rules": [],
    "family": "frozen-base",
    "selection": "insufficient-data"
  },
  "Caribbean Premier League": {
    "samples": 24,
    "rules": [],
    "family": "base-flow",
    "selection": "two-temporal-development-splits",
    "validation": [
      {
        "fraction": 0.67,
        "trainingSamples": 16,
        "testSamples": 8,
        "baseCorrect": 7,
        "correct": 7,
        "delta": 0
      },
      {
        "fraction": 0.8,
        "trainingSamples": 19,
        "testSamples": 5,
        "baseCorrect": 4,
        "correct": 4,
        "delta": 0
      }
    ]
  },
  "Delhi Premier League": {
    "samples": 1,
    "rules": [],
    "family": "frozen-base",
    "selection": "insufficient-data"
  },
  "European T20 Premier League": {
    "samples": 21,
    "rules": [
      {
        "conditions": [
          {
            "feature": "back",
            "threshold": 0.55,
            "op": ">="
          },
          {
            "feature": "oppLay",
            "threshold": 0.5,
            "op": ">="
          }
        ],
        "action": "lay",
        "corrected": 4,
        "support": 8
      }
    ],
    "family": "base-flow",
    "selection": "two-temporal-development-splits",
    "validation": [
      {
        "fraction": 0.67,
        "trainingSamples": 14,
        "testSamples": 7,
        "baseCorrect": 3,
        "correct": 3,
        "delta": 0
      },
      {
        "fraction": 0.8,
        "trainingSamples": 16,
        "testSamples": 5,
        "baseCorrect": 2,
        "correct": 2,
        "delta": 0
      }
    ]
  },
  "European Cricket Series": {
    "samples": 0,
    "rules": [],
    "family": "frozen-base",
    "selection": "insufficient-data"
  },
  "First Class Matches": {
    "samples": 1,
    "rules": [],
    "family": "frozen-base",
    "selection": "insufficient-data"
  },
  "ILT20 Development Tournament": {
    "samples": 5,
    "rules": [],
    "family": "frozen-base",
    "selection": "insufficient-data"
  },
  "International Twenty20 Matches": {
    "samples": 19,
    "rules": [],
    "family": "base-flow",
    "selection": "two-temporal-development-splits",
    "validation": [
      {
        "fraction": 0.67,
        "trainingSamples": 12,
        "testSamples": 7,
        "baseCorrect": 5,
        "correct": 5,
        "delta": 0
      },
      {
        "fraction": 0.8,
        "trainingSamples": 15,
        "testSamples": 4,
        "baseCorrect": 3,
        "correct": 3,
        "delta": 0
      }
    ]
  },
  "Kerala Cricket League": {
    "samples": 15,
    "rules": [],
    "family": "base-flow",
    "selection": "two-temporal-development-splits",
    "validation": [
      {
        "fraction": 0.67,
        "trainingSamples": 10,
        "testSamples": 5,
        "baseCorrect": 5,
        "correct": 5,
        "delta": 0
      },
      {
        "fraction": 0.8,
        "trainingSamples": 12,
        "testSamples": 3,
        "baseCorrect": 3,
        "correct": 3,
        "delta": 0
      }
    ]
  },
  "Metro Bank One Day Cup": {
    "samples": 1,
    "rules": [],
    "family": "frozen-base",
    "selection": "insufficient-data"
  },
  "Metro Bank Womens One Day Cup": {
    "samples": 15,
    "rules": [
      {
        "conditions": [
          {
            "feature": "lay",
            "threshold": 0.1,
            "op": ">="
          }
        ],
        "action": "pnlFade",
        "corrected": 3,
        "support": 14
      }
    ],
    "family": "base-flow",
    "selection": "two-temporal-development-splits",
    "validation": [
      {
        "fraction": 0.67,
        "trainingSamples": 10,
        "testSamples": 5,
        "baseCorrect": 4,
        "correct": 5,
        "delta": 1
      },
      {
        "fraction": 0.8,
        "trainingSamples": 10,
        "testSamples": 5,
        "baseCorrect": 4,
        "correct": 5,
        "delta": 1
      }
    ]
  },
  "Netherlands Topklasse T20": {
    "samples": 7,
    "rules": [
      {
        "conditions": [
          {
            "feature": "activity",
            "threshold": 0.75,
            "op": "<="
          }
        ],
        "action": "backFade",
        "corrected": 4,
        "support": 4
      }
    ],
    "family": "flow-pressure",
    "selection": "two-temporal-development-splits",
    "validation": [
      {
        "fraction": 0.67,
        "trainingSamples": 4,
        "testSamples": 3,
        "baseCorrect": 1,
        "correct": 1,
        "delta": 0
      },
      {
        "fraction": 0.8,
        "trainingSamples": 5,
        "testSamples": 2,
        "baseCorrect": 1,
        "correct": 1,
        "delta": 0
      }
    ]
  },
  "One Day Internationals": {
    "samples": 5,
    "rules": [
      {
        "conditions": [
          {
            "feature": "total",
            "threshold": 0.9,
            "op": ">="
          },
          {
            "feature": "total",
            "threshold": 0.975,
            "op": "<="
          }
        ],
        "action": "backFade",
        "corrected": 3,
        "support": 3
      }
    ],
    "family": "odi-extreme-flow-guard",
    "selection": "two-earlier-zero-regression-odi-cases",
    "validation": [
      {
        "fraction": 0.67,
        "trainingSamples": 3,
        "testSamples": 2,
        "baseCorrect": 0,
        "correct": 0,
        "delta": 0
      },
      {
        "fraction": 0.8,
        "trainingSamples": 4,
        "testSamples": 1,
        "baseCorrect": 0,
        "correct": 1,
        "delta": 1
      }
    ]
  },
  "One Day Matches": {
    "samples": 1,
    "rules": [],
    "family": "frozen-base",
    "selection": "insufficient-data"
  },
  "Sher E Punjab T20 League": {
    "samples": 17,
    "rules": [
      {
        "conditions": [
          {
            "feature": "lay",
            "threshold": 0.1,
            "op": ">="
          },
          {
            "feature": "activitySurplus",
            "threshold": -0.25,
            "op": ">="
          }
        ],
        "action": "activity",
        "corrected": 3,
        "support": 7
      },
      {
        "conditions": [
          {
            "feature": "lay",
            "threshold": 0.9,
            "op": "<="
          },
          {
            "feature": "total",
            "threshold": 0.5,
            "op": ">="
          }
        ],
        "action": "backFade",
        "corrected": 2,
        "support": 4
      }
    ],
    "family": "flow-pressure",
    "selection": "two-temporal-development-splits",
    "validation": [
      {
        "fraction": 0.67,
        "trainingSamples": 11,
        "testSamples": 6,
        "baseCorrect": 3,
        "correct": 3,
        "delta": 0
      },
      {
        "fraction": 0.8,
        "trainingSamples": 13,
        "testSamples": 4,
        "baseCorrect": 2,
        "correct": 2,
        "delta": 0
      }
    ]
  },
  "South Africa T20 Challenge": {
    "samples": 2,
    "rules": [],
    "family": "frozen-base",
    "selection": "insufficient-data"
  },
  "T20 African Continental Cup": {
    "samples": 2,
    "rules": [],
    "family": "frozen-base",
    "selection": "insufficient-data"
  },
  "T20 Matches": {
    "samples": 1,
    "rules": [],
    "family": "frozen-base",
    "selection": "insufficient-data"
  },
  "Tamil Nadu Premier League": {
    "samples": 8,
    "rules": [
      {
        "conditions": [
          {
            "feature": "lay",
            "threshold": 0.1,
            "op": ">="
          },
          {
            "feature": "volume",
            "threshold": 3,
            "op": "<="
          }
        ],
        "action": "back",
        "corrected": 3,
        "support": 3
      }
    ],
    "family": "tnpl-low-volume-back-leader-guard",
    "selection": "two-earlier-zero-regression-tnpl-cases",
    "validation": [
      {
        "fraction": 0.67,
        "trainingSamples": 5,
        "testSamples": 3,
        "baseCorrect": 2,
        "correct": 3,
        "delta": 1
      },
      {
        "fraction": 0.8,
        "trainingSamples": 6,
        "testSamples": 2,
        "baseCorrect": 1,
        "correct": 2,
        "delta": 1
      }
    ]
  },
  "Test Matches": {
    "samples": 5,
    "rules": [],
    "family": "frozen-base",
    "selection": "insufficient-data"
  },
  "The Hundred": {
    "samples": 2,
    "rules": [],
    "family": "frozen-base",
    "selection": "insufficient-data"
  },
  "The Hundred - Womens": {
    "samples": 2,
    "rules": [],
    "family": "frozen-base",
    "selection": "insufficient-data"
  },
  "Unofficial International Matches": {
    "samples": 1,
    "rules": [],
    "family": "frozen-base",
    "selection": "insufficient-data"
  },
  "Uttar Pradesh Premier League": {
    "samples": 10,
    "rules": [
      {
        "conditions": [
          {
            "feature": "activitySurplus",
            "threshold": 0,
            "op": "<="
          }
        ],
        "action": "pnl",
        "corrected": 3,
        "support": 5
      }
    ],
    "family": "flow-pressure",
    "selection": "two-temporal-development-splits",
    "validation": [
      {
        "fraction": 0.67,
        "trainingSamples": 6,
        "testSamples": 4,
        "baseCorrect": 2,
        "correct": 2,
        "delta": 0
      },
      {
        "fraction": 0.8,
        "trainingSamples": 8,
        "testSamples": 2,
        "baseCorrect": 0,
        "correct": 0,
        "delta": 0
      }
    ]
  },
  "Uttarakhand Premier League": {
    "samples": 1,
    "rules": [],
    "family": "frozen-base",
    "selection": "insufficient-data"
  },
  "Women's Asia Cup T20": {
    "samples": 7,
    "rules": [],
    "family": "base-flow",
    "selection": "two-temporal-development-splits",
    "validation": [
      {
        "fraction": 0.67,
        "trainingSamples": 4,
        "testSamples": 3,
        "baseCorrect": 3,
        "correct": 3,
        "delta": 0
      },
      {
        "fraction": 0.8,
        "trainingSamples": 5,
        "testSamples": 2,
        "baseCorrect": 2,
        "correct": 2,
        "delta": 0
      }
    ]
  },
  "Women's Caribbean Premier League": {
    "samples": 5,
    "rules": [],
    "family": "frozen-base",
    "selection": "insufficient-data"
  },
  "Women's One Day Matches": {
    "samples": 2,
    "rules": [],
    "family": "frozen-base",
    "selection": "insufficient-data"
  },
  "Women's T20 County Cup": {
    "samples": 1,
    "rules": [],
    "family": "frozen-base",
    "selection": "insufficient-data"
  },
  "Womens International Twenty20 Matches": {
    "samples": 11,
    "rules": [
      {
        "conditions": [
          {
            "feature": "back",
            "threshold": 0.55,
            "op": ">="
          }
        ],
        "action": "activityFade",
        "corrected": 3,
        "support": 11
      }
    ],
    "family": "flow-pressure",
    "selection": "two-temporal-development-splits",
    "validation": [
      {
        "fraction": 0.67,
        "trainingSamples": 7,
        "testSamples": 4,
        "baseCorrect": 3,
        "correct": 4,
        "delta": 1
      },
      {
        "fraction": 0.8,
        "trainingSamples": 8,
        "testSamples": 3,
        "baseCorrect": 2,
        "correct": 3,
        "delta": 1
      }
    ]
  },
  "Womens One Day Internationals": {
    "samples": 6,
    "rules": [],
    "family": "base-flow",
    "selection": "two-temporal-development-splits",
    "validation": [
      {
        "fraction": 0.67,
        "trainingSamples": 4,
        "testSamples": 2,
        "baseCorrect": 2,
        "correct": 2,
        "delta": 0
      },
      {
        "fraction": 0.8,
        "trainingSamples": 4,
        "testSamples": 2,
        "baseCorrect": 2,
        "correct": 2,
        "delta": 0
      }
    ]
  },
  "World Championship of Legends T20": {
    "samples": 0,
    "rules": [],
    "family": "frozen-base",
    "selection": "insufficient-data"
  }
};
